---
title: "STAT 302"
description: |
  Statistical Software and its Applications
site: distill::distill_website
output:
  distill::distill_article:
    self_contained: false
---

Materials for this course were originally developed by [Bryan Martin](https://bryandmartin.github.io/STAT302/index.html).

# Schedule 

### Week One 

* **M 01/03**: Short Lab 0 assigned
* **W 01/05**: Short Lab 0 due before class; Short lab 1 assigned

### Week Two

* **M 01/10**: Short Lab 1 due before class; Lab 1 assigned 
* **W 01/12**: Short Lab 2 assigned 

### Week Three

* **M 01/17**: No class
* **W 01/19**: Short Lab 2 and Lab 1 due before class; Lab 2 assigned

### Week Four

* **M 01/24**: Lab 2 due before class; Project 1 assigned
* **W 01/26**: No new assignment

### Week Five

* **M 01/31**: Short Lab 3 assigned
* **W 02/02**: Project 1 and Short Lab 3 due before class; Lab 3 assigned

### Week Six

* **M 02/07**: No new assignment
* **W 02/09**: Lab 3 due before class; Project 2 assigned 

### Week Seven

* **M 02/14**: No new assignment
* **W 02/16**: No new assignment

### Week Eight

* **M 02/21**: No class
* **W 02/23**: Project 2 due before class; Short Lab 4 assigned

### Week Nine

* **M 02/28**: Short Lab 4 due before class; Lab 4 assigned
* **W 03/02**: No new assignment

### Week Ten

* **M 03/07**: Lab 4 due before class; Project 3 assigned
* **W 03/09**: No new assignment

### Finals week 

* **W 3/16**: Project 3 due Wednesday at 11:59



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

