---
title: "Syllabus"
description: ''
---

*This syllabus is subject to change.*

# Course Information

**Instructor**: Sarah Teichman (teichs at uw dot edu)

**Time**: Mondays and Wednesdays, 3:30 - 4:50pm

**Location**: SAV 155, on Zoom for the first two class meetings

**Office hours**: T 3-4, F 1:30-3:30 via Zoom [(meeting link)](https://washington.zoom.us/j/3955335000)

**Note**: When emailing either the instructor or grader, please include "[STAT 302]" at the beginning of the email header!
It will help us respond to you faster.

# Overview

This course aims to help you build a foundation of computational skills for data analysis. Data encountered in real world applications are usually context-dependent and messy, breaking many of the assumptions we make in typical statistics courses. Properly analyzing such data can require us to develop and build our own tools--ideally in a way that others are able to use and even extend our methods. Throughout this course, we will practice using computers to help us understand, summarize, visualize, and model complex data in a reproducible way.

Students are assumed to have an introductory knowledge of statistics, but no formal computational training. All material is taught using the R statistical programming language. This course emphasizes:

  * **Application over theory**: This course does not aim to teach you statistics: we will briefly review the theory behind some of the methods covered in the course, but our focus will be implementation and application to data analysis. 
    
  * **Best practices for coding**: We will dedicate a substantial amount of time to concepts such as commenting code, code style, documentation, version control, and related topics. These skills might seem tedious at first, but by building good habits, you will save yourself a lot of time and trouble in the future.
    
  * **"Real world" workflow**: Assignments and projects in this course will ask you to take the tools we study and develop throughout the course and apply them to realistic research problems. You will be asked to practice the full "workflow" of data analysis, from data cleaning and debugging to collaboration and presentation. A well designed and implemented project can demonstrate your practical experience and training to others, including future employers.

# Outline

In this course, we will learn fundamental concepts related to programming, statistical computing, and data analysis. Points of
emphasis include:

  * Programming fundamentals
    
  * Data visualization
  
  * Data cleaning/manipulation
  
  * Version control and git
  
  * Debugging
  
  * Computation for statistical inference
  
  * Computation for statistical prediction

# Course structure

Typically, each 80 minute class session will be broken up into a 45 minute lecture, a 5 minute break, and a 30 minute lab. Lab time will be an opportunity for you to practice coding, work collaboratively on assignments, and ask for help. Most topics in lecture will last two class periods. 

  * **Short Labs**: You will be assigned six short labs throughout the quarter. These are designed to be completed during lab or shortly after and will be due at the start of the next class. At the end of the quarter, your lowest Short Lab grade will be dropped. They will be graded on the following two point scale:
  
    * 0: indicates incomplete or unacceptable work
    * 1: indicates a good faith effort towards completing >75% of the assignment
    * 2: indicates a good faith effort towards completing the entire assignment.

  * **Labs**: You will be assigned three labs throughout the quarter. These are extended, more complicated assignments that you will likely not be able to complete during class. They will be due at the start of the next class.
  
  * **Projects**: Instead of exams, you will be assigned three projects throughout the course. We will dedicate at least two lab sessions to each project and you will have about one week to complete each.
  
    * Project 1 focuses on data manipulation and visualization. 
    * Project 2 focuses on practicing real-world data analysis skills. 
    * Project 3 brings together several of the topics that you've learned.

  * **Late Work**: In general, the late policy is as follows: Any assignment that is received late but less than 24 hours late will receive a grade penalty of 25%. Any assignment that is received 24–48 hours late will receive a grade penalty of 50%. Assignments will not be accepted more than 48 hours late. **That said, if you communicate directly with me before an assignment is due, I will often be willing to relax a deadline.**

# Grading

Your final grade will be calculated as follows:

  * 20%: Short Labs
  * 20%: Labs
  * 15%: Minimum grade from Project 1 and Project 2
  * 25%: Maximum grade from Project 1 and Project 2
  * 20%: Project 3
  * 2% (extra credit): Discussion board participation. Both questions and answers will be considered.
  

# Returning to in-person learning

### Winter 2022
  Due to the recent surge in COVID cases, most UW courses will be online for the first week of the quarter, including this one. Zoom links to the first two courses can be found in the 'Zoom' tab on Canvas. After the first week we will transition to in-person learning, unless the guidance from the university changes. 

### Expectations
  The COVID-19 pandemic has and will continue to present many of us with unforeseen difficulties.  I encourage all of you to prioritize the health and safety of yourselves and those around you and would be happy to make accommodations that help you to do so.
In addition, I hope that we can be patient with one another as we continue transitioning back to in-person learning, as it is likely that not everything will go to plan. Please feel free to reach out to me via email at any point to discuss any concerns you may have about the course.

### Keeping each other safe
  I am thrilled to be teaching in person and I hope you are excited to be back on campus as well. As we return to physical classrooms, please be respectful of your classmates' boundaries and precautions--we are all readjusting to in-person learning. In addition, I hope we will all make every effort to keep ourselves and our classmates safe. If you test positive or are exposed to possible infection, I encourage you to err on the side of caution with regards to attending classes and would be happy to make accomodations that allow you to do so. I will make high-quality recordings of lecture and additional office hours available to students that are absent due to quarantine.


# Classroom environment
  
### Names & Pronouns
  Everyone deserves to be addressed as they would like. Feel free to send us your preferred name and correct pronouns at any time.

### Personal computers
If you do not have a personal computer, you can borrow one for free from UW through the Student Technology Loan Program. In general, if you have trouble accessing a computer, please contact me so we can make sure you have the resources you need to learn.

### Feedback
  I encourage and appreciate your feedback throughout the quarter. You are welcome to provide feedback on any aspect of the course at any time via email or in person. If you would prefer to do so confidentially, you can do so through the form [here](https://forms.gle/MiVUgmhwfHSDG8Fm8).

### Collaboration
  On most assignments, collaboration is allowed and encouraged. You may discuss problems, approaches, and solutions with your classmates. Acceptable collaboration is limited to your classmates in this course and you must clearly include on any collaborative work the name(s) of anyone with whom you worked. Additionally, all submitted work must be your own; you should not submit code or answers copied from any resource including your classmates. Plagiarism and cheating is easy for us to detect and can lead to serious negative consequences for you (see Academic Integrity below). If you have any questions regarding this policy, please ask for clarification.

### Discussion board
  You are encouraged to participate on the discussion board by posting questions about assignments and answering questions from other students. Posts may not include substantial amounts of code that can be used for a solution to any problem, but may include code snippets within reason. Participation, in the form of both questions and answers, can earn you up to 2% extra credit for your final grade. Posts will be evaluated based on how substantive and helpful they are to the class.

### Academic misconduct
  Academic integrity is essential to this course and to your learning. On certain assignments, collaboration is allowed and encouraged when following the collaboration policy outlined above. Violations of the academic integrity policy include but are not limited to: copying from a peer, collaborating where it is not allowed, copying from an online resource, using a solutions manual, and using resources from a previous iteration of the course. Anything found in violation of this policy will be automatically given a score of 0 with no exceptions. If the situation merits, it will also be reported to the UW Student Conduct Office, at which point it will be out of my hands. If you have any questions about this policy, please do not hesitate to reach out and ask.

  The university’s policy on plagiarism and academic misconduct is a part of the Student Conduct Code, which cites the definition of academic misconduct in the WAC 478-121. (WAC is an abbreviation for the Washington Administrative Code, the set of state regulations for the university. The entire chapter of the WAC on the student conduct code is here http://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html) According to this section of the WAC, academic misconduct includes: 

  *“Cheating”—such as “unauthorized assistance in taking quizzes”, “Falsification” “which is the intentional use or submission of falsified data, records, or other information including, but not limited to, records of internship or practicum experiences or attendance at any required event(s), or scholarly research”; and “Plagiarism” which includes “[t]he use, by paraphrase or direct quotation, of the published or unpublished work of another person without full and clear acknowledgment.”* 

  The UW Libraries have a useful guide for students at http://www.lib.washington.edu/teaching/plagiarism Students found to have engaged in academic misconduct may receive a zero on the assignment (or other possible outcome).

### Conduct
The University of Washington Student Conduct Code (WAC 478-121) defines prohibited academic and behavioral conduct and describes how the University holds students accountable as they pursue their academic goals. Allegations of misconduct by students may be referred to the appropriate campus office for investigation and resolution. More information can be found online at https://www.washington.edu/studentconduct/.

### Disability Resources
Your experience in this class is important to me. It is the policy and practice of the University of Washington to create inclusive and accessible learning environments consistent with federal and state law. If you have already established accommodations with Disability Resources for Students (DRS), please activate your accommodations via myDRS so we can discuss how they will be implemented in this course.
	
If you have not yet established services through DRS, but have a temporary health condition or permanent disability that requires accommodations (conditions include but not limited to; mental health, attention-related, learning, vision, hearing, physical or health impacts), contact DRS directly to set up an Access Plan. DRS facilitates the interactive process that establishes reasonable accommodations. Contact DRS at http://depts.washington.edu/uwdrs/
	
### Diversity, equity and inclusion
Diverse backgrounds, embodiments, and experiences are essential to the critical thinking endeavor at the heart of university education. Therefore, I expect you to follow the UW Student Conduct Code in your interactions with your colleagues and me in this course by respecting the many social and cultural differences among us, which may include, but are not limited to: age, cultural background, disability, ethnicity, family status, gender identity and presentation, citizenship and immigration status, national origin, race, religious and political beliefs, sex, sexual orientation, socioeconomic status, and veteran status.

### Religious accommodations
Washington state law requires that UW develop a policy for accommodation of student absences or significant hardship due to reasons of faith or conscience, or for organized religious activities. The UW’s policy, including more information about how to request an accommodation, is available at https://registrar.washington.edu/staffandfaculty/religious-accommodations-policy/.

Accommodations must be requested within the first two weeks of this course using the  https://registrar.washington.edu/students/religious-accommodations-request/

### Student privacy
Note that the software used in this class (e.g. Canvas, Zoom, Panopto) when used with our UW Net IDs, are FERPA compliant (https://registrar.washington.edu/students/ferpa/). This means they do not monitor student use of their service and they do not share student data with third parties. 

Sharing recordings and other class materials outside of class that include personally identifiable student information without the written consent of those students is a violation of FERPA. State law requires consent from people to be recorded (https://apps.leg.wa.gov/rcw/default.aspx?cite=9.73.030), please note that (1) that your participation in this class indicates your consent for course activities to be recorded, (2) you are not permitted to make your own recordings without consent from the instructor and everyone else involved, and (3) that the instructor’s recordings will be available for later playback only to students taking the course. For more information about privacy concerns, review the UW Privacy Office policies (https://privacy.uw.edu/policies/best-practices-online-conferencing/), or contact Helen Garrett, the UW's FERPA Officer.

# Links and other resources

* [Canvas Page](https://canvas.uw.edu/courses/1519530)

* [Install R](https://cran.r-project.org/)

* [Install RStudio](https://rstudio.com/products/rstudio/download/#download)

* [Install RMarkdown](https://bookdown.org/yihui/rmarkdown/installation.html#installation)

* [RStudio Cheatsheets](https://rstudio.com/resources/cheatsheets/)
